- name: Install baseline packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - git
    - gnupg
    - htop
    - ncdu
    - python-pip
    - software-properties-common
    - sudo
    - tig
    - tmux
    - vim
    - wget

- name: Install /etc/resolv.conf
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
