version: '3'
services:
  backend:
    image: registry:2
    volumes:
      - "/home/deploy/docker/volumes/registry:/var/lib/registry"
    ports:
      - "5000:5000"
    deploy:
      placement:
        constraints:
          - node.labels.deploy-registry==true
  frontend:
    image: klausmeyer/docker-registry-browser
    environment:
      - "DOCKER_REGISTRY_URL=http://backend:5000"
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints:
          - node.labels.deploy-registry==true
