version: "3"
services:
  backend:
    image: registry:2
    environment:
      - "REGISTRY_STORAGE_DELETE_ENABLED=true"
    volumes:
      - "/home/deploy/docker/volumes/registry:/var/lib/registry"
    ports:
      - "5000:5000"
    networks:
      - homelab
    deploy:
      placement:
        constraints:
          - node.labels.deploy-registry==true

  frontend:
    image: klausmeyer/docker-registry-browser
    environment:
      - "DOCKER_REGISTRY_URL=http://backend:5000"
      - "ENABLE_DELETE_IMAGES=true"
      - "PUBLIC_REGISTRY_URL=registry.homelab.klaus-meyer.net:5000"
    networks:
      - homelab
    deploy:
      labels:
        - traefik.backend.loadbalancer.swarm=true
        - traefik.backend=registry-frontend
        - traefik.frontend.rule=Host:registry.homelab.klaus-meyer.net
        - traefik.port=8080
      replicas: 4

networks:
  homelab:
    external: true
