version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    ports:
      - "80:80"
    networks:
      - homelab
    deploy:
      mode: global

networks:
  homelab:
    external: true
